# GET  http://localhost:3001/api/persons

POST  http://localhost:3001/api/persons
content-type: application/json

{
    "id": 5,
    "name": "Albert Einstein",
     "date": "2019-05-30T17:30:31.098Z",
    "number": "12-43-20455731"
}
